import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { MemberAuthGuard } from './guards/member-auth.guard';
import {
  CinVerificationComponent,
  BrowseGroupsComponent,
  MemberChatbotComponent,
  MemberMessagesComponent,
  MemberProfileComponent,
  DoctorDirectoryComponent,
  ExcludedConditionsComponent,
  FaceRecognitionLoginComponent,
  FirstPaymentComponent,
  ForgotPasswordComponent,
  GroupsDashboardComponent,
  HealthToolsHubComponent,
  HomeComponent,
  MedicationRecommendationsComponent,
  MedicalHistoryComponent,
  MemberProfileOnboardingComponent,
  MemberAppComponent,
  MemberSignInComponent,
  MemberRootComponent,
  PaymentHistoryComponent,
  InvitationQrComponent,
  PharmacyQrComponent,
  PlanSelectionComponent,
  PriceCalculationComponent,
  RewardsChallengeComponent,
  TelemedicineBookingComponent,
  VideoCallComponent,
  WaitingApprovalComponent,
  WelcomeComponent,
  CreateAccountComponent,
} from './member';
import { SubmitClaimComponent } from './member/app-pages/Score/submit-claim/submit-claim';
import { ClaimListComponent } from './member/app-pages/Score/claim-list/claim-list';
import { MemberRewardsComponent } from './member/app-pages/Score/member-reward/member-reward';

const routes: Routes = [
  {
    path: 'app',
    component: MemberAppComponent,
    canActivate: [MemberAuthGuard],
    children: [
      { path: '', component: GroupsDashboardComponent },
      { path: 'submit-claim', component: SubmitClaimComponent },
      {
        path: 'claims/my',
        component: ClaimListComponent,
      },
      { path: 'rewards', component: MemberRewardsComponent },
      { path: 'doctors', component: DoctorDirectoryComponent },
      { path: 'create-join-group', component: BrowseGroupsComponent },
      { path: 'browse-groups', component: BrowseGroupsComponent },
      { path: 'medications', component: MedicationRecommendationsComponent },
      { path: 'health', component: HealthToolsHubComponent },
      { path: 'pharmacy-qr', component: PharmacyQrComponent },
      { path: 'payment-history', component: PaymentHistoryComponent },
      { path: 'telemedicine-booking', component: TelemedicineBookingComponent },
      { path: 'video-call/:appointmentId', component: VideoCallComponent },
      { path: 'profile', component: MemberProfileComponent },
      { path: 'messages', component: MemberMessagesComponent },
      { path: 'group-chat', component: MemberMessagesComponent },
      { path: 'invite-qr', component: InvitationQrComponent },
      { path: 'chatbot', component: MemberChatbotComponent },
    ],
  },
  {
    path: '',
    component: MemberRootComponent,
    children: [
      {
        path: 'member-app',
        component: MemberAppComponent,
        canActivate: [MemberAuthGuard],
        children: [
          { path: '', component: GroupsDashboardComponent },
          { path: 'submit-claim', component: SubmitClaimComponent },
          {
    path: 'claims/my',
    component: ClaimListComponent,
  },
  {
    path: 'claims',
    redirectTo: 'claims/my',
    pathMatch: 'full',
  },
          { path: 'rewards', component: RewardsChallengeComponent },
          { path: 'doctors', component: DoctorDirectoryComponent },
          { path: 'create-join-group', component: BrowseGroupsComponent },
          { path: 'browse-groups', component: BrowseGroupsComponent },
          { path: 'medications', component: MedicationRecommendationsComponent },
          { path: 'health', component: HealthToolsHubComponent },
          { path: 'pharmacy-qr', component: PharmacyQrComponent },
          { path: 'payment-history', component: PaymentHistoryComponent },
          { path: 'telemedicine-booking', component: TelemedicineBookingComponent },
          { path: 'video-call/:appointmentId', component: VideoCallComponent },
          { path: 'profile', component: MemberProfileComponent },
          { path: 'messages', component: MemberMessagesComponent },
          { path: 'group-chat', component: MemberMessagesComponent },
          { path: 'invite-qr', component: InvitationQrComponent },
          { path: 'chatbot', component: MemberChatbotComponent },
        ],
      },
      { path: 'dashboard', redirectTo: 'member-app', pathMatch: 'full' },
      { path: '', pathMatch: 'full', redirectTo: 'home' },
      { path: 'home', component: HomeComponent },
      { path: 'sign-in', component: MemberSignInComponent },
      { path: 'forgot-password', component: ForgotPasswordComponent },
      { path: 'face-login', component: FaceRecognitionLoginComponent },
      { path: 'verify-cin', component: CinVerificationComponent },
      { path: 'medical-history', component: MedicalHistoryComponent },
      { path: 'excluded', component: ExcludedConditionsComponent },
      { path: 'calculating', component: PriceCalculationComponent },
      { path: 'select-plan', component: PlanSelectionComponent },
      { path: 'waiting-approval', component: WaitingApprovalComponent },
      { path: 'member-profile', component: MemberProfileOnboardingComponent },
      { path: 'browse-groups', component: BrowseGroupsComponent },
      { path: 'first-payment', component: FirstPaymentComponent },
      { path: 'create-account', component: CreateAccountComponent },
    ],
  },
  { path: '**', redirectTo: '' },
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
